/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.avaliacao.continuada;
// IMPORTANDO CLASSE RANDOM
import java.util.Random;

/**
 *
 * @author Cliente
 */
public class GerenciadorCpuMemoriaDisco extends javax.swing.JFrame {

    /**
     * Creates new form GerenciadorCpuMemoriaDisco
     */
    public GerenciadorCpuMemoriaDisco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbarCpu = new javax.swing.JProgressBar();
        pbarMemoria = new javax.swing.JProgressBar();
        pbarDisco = new javax.swing.JProgressBar();
        btnLeituaDeDados = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblCpuTxtProgressBar = new javax.swing.JLabel();
        lblRamTxtProgressBar = new javax.swing.JLabel();
        lblDiscTxtProgressBar = new javax.swing.JLabel();
        panelCpu = new javax.swing.JPanel();
        lblCpuTxtGroupBox = new javax.swing.JLabel();
        lblTxtMaxCpu = new javax.swing.JLabel();
        lblTxtMinCpu = new javax.swing.JLabel();
        lblCpuMax = new javax.swing.JLabel();
        lblCpuMin = new javax.swing.JLabel();
        lblTxtMedCpu = new javax.swing.JLabel();
        lblCpuMed = new javax.swing.JLabel();
        panelDisc = new javax.swing.JPanel();
        lblDiscTxtGroupBox = new javax.swing.JLabel();
        lblTxtMaxDisc = new javax.swing.JLabel();
        lblTxtMinDisc = new javax.swing.JLabel();
        lblDiscMax = new javax.swing.JLabel();
        lblDiscMin = new javax.swing.JLabel();
        lblTxtMedDisc = new javax.swing.JLabel();
        lblDiscMed = new javax.swing.JLabel();
        panelRam = new javax.swing.JPanel();
        lblRamTxtGroupBox = new javax.swing.JLabel();
        lblTxtMaxRam = new javax.swing.JLabel();
        lblTxtMinRam = new javax.swing.JLabel();
        lblRamMax = new javax.swing.JLabel();
        lblRamMin = new javax.swing.JLabel();
        lblTxtMedRam = new javax.swing.JLabel();
        lblRamMed = new javax.swing.JLabel();
        panelUltilizacao = new javax.swing.JPanel();
        lblTxtUltiTitulo = new javax.swing.JLabel();
        lblUltCpu = new javax.swing.JLabel();
        lblRamTxtUltilizacao = new javax.swing.JLabel();
        lblDiscTxtUltilizacao = new javax.swing.JLabel();
        lblCpuTxtUltilizacao = new javax.swing.JLabel();
        lblUltRam = new javax.swing.JLabel();
        lblUltDisc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        pbarCpu.setStringPainted(true);

        pbarMemoria.setStringPainted(true);

        pbarDisco.setStringPainted(true);

        btnLeituaDeDados.setText("Ler dados do computador");
        btnLeituaDeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituaDeDadosActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(222, 99, 3));
        lblTitulo.setText("GERENCIADOR DE TAREFAS");

        lblCpuTxtProgressBar.setText("CPU");

        lblRamTxtProgressBar.setText("RAM");

        lblDiscTxtProgressBar.setText("DISCO");

        panelCpu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCpu.setForeground(new java.awt.Color(255, 255, 255));

        lblCpuTxtGroupBox.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCpuTxtGroupBox.setForeground(new java.awt.Color(51, 102, 255));
        lblCpuTxtGroupBox.setText("CPU");

        lblTxtMaxCpu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMaxCpu.setText("Máximo");

        lblTxtMinCpu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMinCpu.setText("Mínimo");

        lblCpuMax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCpuMax.setText("---");

        lblCpuMin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCpuMin.setText("---");

        lblTxtMedCpu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMedCpu.setText("Média");

        lblCpuMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCpuMed.setText("---");

        javax.swing.GroupLayout panelCpuLayout = new javax.swing.GroupLayout(panelCpu);
        panelCpu.setLayout(panelCpuLayout);
        panelCpuLayout.setHorizontalGroup(
            panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCpuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCpuLayout.createSequentialGroup()
                        .addComponent(lblTxtMaxCpu)
                        .addGap(33, 33, 33)
                        .addComponent(lblCpuMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCpuLayout.createSequentialGroup()
                        .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTxtMedCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTxtMinCpu))
                        .addGap(36, 36, 36)
                        .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCpuMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpuMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblCpuTxtGroupBox))
                .addGap(75, 75, 75))
        );
        panelCpuLayout.setVerticalGroup(
            panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpuTxtGroupBox)
                .addGap(18, 18, 18)
                .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMaxCpu)
                    .addComponent(lblCpuMax))
                .addGap(18, 18, 18)
                .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMinCpu)
                    .addComponent(lblCpuMin))
                .addGap(18, 18, 18)
                .addGroup(panelCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpuMed)
                    .addComponent(lblTxtMedCpu))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelDisc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDiscTxtGroupBox.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDiscTxtGroupBox.setForeground(new java.awt.Color(51, 255, 51));
        lblDiscTxtGroupBox.setText("DISCO");

        lblTxtMaxDisc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMaxDisc.setText("Máximo");

        lblTxtMinDisc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMinDisc.setText("Mínimo");

        lblDiscMax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiscMax.setText("---");

        lblDiscMin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiscMin.setText("---");

        lblTxtMedDisc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMedDisc.setText("Média");

        lblDiscMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiscMed.setText("---");

        javax.swing.GroupLayout panelDiscLayout = new javax.swing.GroupLayout(panelDisc);
        panelDisc.setLayout(panelDiscLayout);
        panelDiscLayout.setHorizontalGroup(
            panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDiscLayout.createSequentialGroup()
                        .addComponent(lblTxtMaxDisc)
                        .addGap(33, 33, 33)
                        .addComponent(lblDiscMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDiscLayout.createSequentialGroup()
                        .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTxtMedDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTxtMinDisc))
                        .addGap(36, 36, 36)
                        .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDiscMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiscMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblDiscTxtGroupBox))
                .addGap(75, 75, 75))
        );
        panelDiscLayout.setVerticalGroup(
            panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiscTxtGroupBox)
                .addGap(18, 18, 18)
                .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMaxDisc)
                    .addComponent(lblDiscMax))
                .addGap(18, 18, 18)
                .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMinDisc)
                    .addComponent(lblDiscMin))
                .addGap(18, 18, 18)
                .addGroup(panelDiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscMed)
                    .addComponent(lblTxtMedDisc))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelRam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRamTxtGroupBox.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRamTxtGroupBox.setForeground(new java.awt.Color(204, 0, 204));
        lblRamTxtGroupBox.setText("RAM");

        lblTxtMaxRam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMaxRam.setText("Máximo");

        lblTxtMinRam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMinRam.setText("Mínimo");

        lblRamMax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRamMax.setText("---");

        lblRamMin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRamMin.setText("---");

        lblTxtMedRam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTxtMedRam.setText("Média");

        lblRamMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRamMed.setText("---");

        javax.swing.GroupLayout panelRamLayout = new javax.swing.GroupLayout(panelRam);
        panelRam.setLayout(panelRamLayout);
        panelRamLayout.setHorizontalGroup(
            panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRamLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRamLayout.createSequentialGroup()
                        .addComponent(lblTxtMaxRam)
                        .addGap(33, 33, 33)
                        .addComponent(lblRamMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRamLayout.createSequentialGroup()
                        .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTxtMedRam, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTxtMinRam))
                        .addGap(36, 36, 36)
                        .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRamMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRamMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblRamTxtGroupBox))
                .addGap(75, 75, 75))
        );
        panelRamLayout.setVerticalGroup(
            panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRamTxtGroupBox)
                .addGap(18, 18, 18)
                .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMaxRam)
                    .addComponent(lblRamMax))
                .addGap(18, 18, 18)
                .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtMinRam)
                    .addComponent(lblRamMin))
                .addGap(18, 18, 18)
                .addGroup(panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRamMed)
                    .addComponent(lblTxtMedRam))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelUltilizacao.setBackground(new java.awt.Color(255, 255, 255));
        panelUltilizacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTxtUltiTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTxtUltiTitulo.setForeground(new java.awt.Color(222, 99, 3));
        lblTxtUltiTitulo.setText("UTILIZAÇÃO %");

        lblUltCpu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUltCpu.setForeground(new java.awt.Color(0, 0, 0));
        lblUltCpu.setText("0%");

        lblRamTxtUltilizacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRamTxtUltilizacao.setForeground(new java.awt.Color(0, 0, 0));
        lblRamTxtUltilizacao.setText("RAM");

        lblDiscTxtUltilizacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDiscTxtUltilizacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDiscTxtUltilizacao.setText("DISCO");

        lblCpuTxtUltilizacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCpuTxtUltilizacao.setForeground(new java.awt.Color(0, 0, 0));
        lblCpuTxtUltilizacao.setText("CPU");

        lblUltRam.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUltRam.setForeground(new java.awt.Color(0, 0, 0));
        lblUltRam.setText("0%");

        lblUltDisc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUltDisc.setForeground(new java.awt.Color(0, 0, 0));
        lblUltDisc.setText("0%");

        javax.swing.GroupLayout panelUltilizacaoLayout = new javax.swing.GroupLayout(panelUltilizacao);
        panelUltilizacao.setLayout(panelUltilizacaoLayout);
        panelUltilizacaoLayout.setHorizontalGroup(
            panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTxtUltiTitulo)
                    .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                        .addComponent(lblDiscTxtUltilizacao)
                        .addGap(46, 46, 46)
                        .addComponent(lblUltDisc))
                    .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                        .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRamTxtUltilizacao, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblCpuTxtUltilizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46)
                        .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUltRam)
                            .addComponent(lblUltCpu))))
                .addGap(70, 70, 70))
        );
        panelUltilizacaoLayout.setVerticalGroup(
            panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTxtUltiTitulo)
                .addGap(40, 40, 40)
                .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltCpu)
                    .addComponent(lblCpuTxtUltilizacao))
                .addGap(18, 18, 18)
                .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRamTxtUltilizacao)
                    .addComponent(lblUltRam))
                .addGroup(panelUltilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblDiscTxtUltilizacao))
                    .addGroup(panelUltilizacaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUltDisc)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiscTxtProgressBar)
                            .addComponent(lblCpuTxtProgressBar)
                            .addComponent(lblRamTxtProgressBar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pbarDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLeituaDeDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pbarMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pbarCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelUltilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblCpuTxtProgressBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbarCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblRamTxtProgressBar)
                        .addGap(3, 3, 3)
                        .addComponent(pbarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panelDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiscTxtProgressBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeituaDeDados)
                        .addGap(18, 18, 18)
                        .addComponent(panelUltilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // CRIANDO VARIAVEIS GLOBAIS
    
    Integer maxCpu = 0,minCpu = 100,contador = 0,somaCpu = 0,maxRam = 0,minRam = 100,somaRam = 0,maxDisc = 0,minDisc = 100,somaDisc = 0;
    Double medCpu,medRam,medDisc;
    
    private void btnLeituaDeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituaDeDadosActionPerformed
        //CRIANDO VARIAVEL ALEATORIO
        Random aleatorio = new Random();
        
        //CRIANDO VARIAVEIS ALEATORIA PARA VALOR DE CPU, RAM, DISCO
        Integer cpuBarRandom = aleatorio.nextInt(101);
        Integer ramBarRandom = aleatorio.nextInt(101);
        Integer discBarRandom = aleatorio.nextInt(101);
        
        //SOMANDO O TODAS AS VARIAVEIS ALEATORIA A CADA CLICK NO BOTÃO
        somaCpu += cpuBarRandom;
        somaRam += ramBarRandom;
        somaDisc += discBarRandom;
        
        // CONTADOR DE CLIQUES NO BOTÃO
        contador++;
        
        //MÉDIA DA CPU, RAM, DISCO
        medCpu = Double.valueOf(somaCpu) / Double.valueOf(contador);
        lblCpuMed.setText(String.format("%.1f ", medCpu));
        
        medRam = Double.valueOf(somaRam) / Double.valueOf(contador);
        lblRamMed.setText(String.format("%.1f ", medRam));
        
        medDisc = Double.valueOf(somaDisc) / Double.valueOf(contador);
        lblDiscMed.setText(String.format("%.1f ", medDisc));
        
        //ATRIBUINDO VALOR ALEATORIO PARA AS BARRA DE PROGRESSO
        pbarCpu.setValue(cpuBarRandom);
        pbarMemoria.setValue(ramBarRandom);
        pbarDisco.setValue(discBarRandom);
        
        //ATRIBUINDO VALORES ALEATORIOS A PAINEL GERAL
        lblUltCpu.setText(String.format("%d %%", cpuBarRandom));
        lblUltRam.setText(String.format("%d %%", ramBarRandom));
        lblUltDisc.setText(String.format("%d %%", discBarRandom));
        
        // DEFININDO MINIMO E MAXIMO DE CPU, RAM, DISCO
        if (cpuBarRandom > maxCpu){
            maxCpu = cpuBarRandom;
            lblCpuMax.setText(String.format("%d %%", maxCpu));
        }
        if (cpuBarRandom < minCpu){
            minCpu = cpuBarRandom;
            lblCpuMin.setText(String.format("%d %%", minCpu));
        }
        
        if (ramBarRandom > maxRam){
            maxRam = ramBarRandom;
            lblRamMax.setText(String.format("%d %%", maxRam));
        }
        if (ramBarRandom < minRam){
            minRam = ramBarRandom;
            lblRamMin.setText(String.format("%d %%", minRam));
        }
        
        if (discBarRandom > maxDisc){
            maxDisc = discBarRandom;
            lblDiscMax.setText(String.format("%d %%", maxDisc));
        }
        if (discBarRandom < minDisc){
            minDisc = discBarRandom;
            lblDiscMin.setText(String.format("%d %%", minDisc));
        }
    }//GEN-LAST:event_btnLeituaDeDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorCpuMemoriaDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorCpuMemoriaDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorCpuMemoriaDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorCpuMemoriaDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorCpuMemoriaDisco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeituaDeDados;
    private javax.swing.JLabel lblCpuMax;
    private javax.swing.JLabel lblCpuMed;
    private javax.swing.JLabel lblCpuMin;
    private javax.swing.JLabel lblCpuTxtGroupBox;
    private javax.swing.JLabel lblCpuTxtProgressBar;
    private javax.swing.JLabel lblCpuTxtUltilizacao;
    private javax.swing.JLabel lblDiscMax;
    private javax.swing.JLabel lblDiscMed;
    private javax.swing.JLabel lblDiscMin;
    private javax.swing.JLabel lblDiscTxtGroupBox;
    private javax.swing.JLabel lblDiscTxtProgressBar;
    private javax.swing.JLabel lblDiscTxtUltilizacao;
    private javax.swing.JLabel lblRamMax;
    private javax.swing.JLabel lblRamMed;
    private javax.swing.JLabel lblRamMin;
    private javax.swing.JLabel lblRamTxtGroupBox;
    private javax.swing.JLabel lblRamTxtProgressBar;
    private javax.swing.JLabel lblRamTxtUltilizacao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTxtMaxCpu;
    private javax.swing.JLabel lblTxtMaxDisc;
    private javax.swing.JLabel lblTxtMaxRam;
    private javax.swing.JLabel lblTxtMedCpu;
    private javax.swing.JLabel lblTxtMedDisc;
    private javax.swing.JLabel lblTxtMedRam;
    private javax.swing.JLabel lblTxtMinCpu;
    private javax.swing.JLabel lblTxtMinDisc;
    private javax.swing.JLabel lblTxtMinRam;
    private javax.swing.JLabel lblTxtUltiTitulo;
    private javax.swing.JLabel lblUltCpu;
    private javax.swing.JLabel lblUltDisc;
    private javax.swing.JLabel lblUltRam;
    private javax.swing.JPanel panelCpu;
    private javax.swing.JPanel panelDisc;
    private javax.swing.JPanel panelRam;
    private javax.swing.JPanel panelUltilizacao;
    private javax.swing.JProgressBar pbarCpu;
    private javax.swing.JProgressBar pbarDisco;
    private javax.swing.JProgressBar pbarMemoria;
    // End of variables declaration//GEN-END:variables
}
